musicapp/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

musicapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

musicapp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
	validates :email, :session_token, presence: true, uniqueness: true
	validates :password_digest, presence: true
	validates :password, length: { minimum: 6 }, allow_nil: true

	before_validation :ensure_session_token

	attr_reader :password

	def self.find_by_credentials(email, password)
		user = User.find_by(email: email)
		if user && user.is_password?(password) #Ruby && is short circuit, so if user.nil? then will not evaluate right side, will not trigger NoMethodError for nil:NilClass
			user
		else
			nil
		end
	end

	def password=(password)
		@password = password
		self.password_digest = BCrypt::Password.create(password)
	end

	def is_password?(password)
		password_obj = BCrypt::Password.new(self.password_digest)
		password_obj.is_password?(password)
	end

	def reset_session_token!
		self.session_token = generate_unique_session_token
		self.save!
		self.session_token
	end

	private

	def generate_unique_session_token
		# debugger
		possible_session_token = SecureRandom::urlsafe_base64
		while User.find_by(session_token: possible_session_token) 
			possible_session_token = SecureRandom::urlsafe_base64
		end
		possible_session_token
	end

	def ensure_session_token
		self.session_token ||= generate_unique_session_token #QQQ: How come this doesn't work for implicit self (omit self.)?
	end
end

musicapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	skip_before_action :verify_authenticity_token
	helper_method :current_user #exposes this method to views layer, so it can check if there is a current user. Access user attributes for display / logic, and render login/logout based on whether we have a current user.

	def login!(user)
		session[:session_token] = user.reset_session_token!
	end

	def current_user
		@current_user ||= User.find_by(session_token: session[:session_token])
	end

	def logged_in?
		!!@current_user
	end

	def logout! #QQQ logout! should not take an argument, correct? Logout should specifically logout the current_user which should not require an argument.
		current_user.reset_session_token if logged_in?
		session[:session_token] = nil
		@current_user = nil
	end
end

musicapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new #display login page
		@user = User.new
		render :new
	end

	def create #attempt login
		email = params[:user][:email]
		password = params[:user][:password]
		@user = User.find_by_credentials(email, password)

		if @user #if user exists...
			# debugger
			login!(@user) #generate new session_token for @user, and save it to session's session_token so they match
			redirect_to user_url(@user) #show userpage.
		
		else #if login not successful, reattempt login
			@user = User.new(email: email)
			render :new
		end

	end

	def destroy #logout
		logout!
		redirect_to new_session_url
	end

end

musicapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new #display signup page
		@user = User.new
		render :new
	end

	def create #attempt signup
		@user = User.new(user_params)
		debugger
		if @user.save #if user successfully created...
			login!(@user) #generate new session token for user and match the session's session token to that.
			redirect_to user_url(@user) #show userpage.
		else #if signup not successful, reattempt signup
			@user = User.new(email: user_params[:email])
			render :new
		end
	end

	def show #display specific userpage
		@user = User.find_by(id: params[:id])
		if @user #if user found, show.
			render :show
		else #if user not found, display login page
			redirect_to new_session_url
		end
	end

	def user_params
		params.require(:user).permit(:email, :password, :session_token)
	end
end

musicapp/app/helpers/application_helper.rb
module ApplicationHelper
end

musicapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <h1>&#127911; + &#128524;</h1>

    <%= yield %>
    <br/>

    <% if current_user %>
      <form action="<%= session_url =%>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Logout">
      </form>
    <% end %>
  </body>
</html>

musicapp/app/views/users/new.html.erb
<h2>Create an account.</h2>

<form action="<%= users_url %>" method="POST" >
	<label>Email: 
		<input type="text" name= "user[email]" value="<%= @user.email %>">
	</label>
	<br/>

	<label>Password: 
		<input type="password" name="user[password]" value="">
	</label>
	<br/>
	<br/>

	<input type="submit" value="Register">
</form>
<form action="<%= new_session_url %>" method="GET">
	<input type="submit" value="Log In"> 
</form>

musicapp/app/views/users/show.html.erb
<h1>&#127911; + &#128524;</h1>

<h2>Welcome, <%= @user.email %></h2>